" plug settings
if empty(glob("$HOME/.vim/autoload/plug.vim"))
    silent !curl --fail --location --output $HOME/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin()
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdtree', {'on': 'NERDTreeToggle'}
Plug 'bling/vim-bufferline'
Plug 'airblade/vim-gitgutter'
Plug 'Chiel92/vim-autoformat'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'vim-syntastic/syntastic'
Plug 'tpope/vim-commentary'
Plug 'mbbill/undotree'
Plug 'Yggdroot/indentLine'
Plug 'majutsushi/tagbar'
Plug 'xuhdev/SingleCompile'

Plug 'chrisbra/csv.vim'

if v:version < 705
    Plug 'vim-scripts/AutoComplPop'
else
    Plug 'codota/tabnine-nvim', {'do': './dl_binaries.sh'}
endif

Plug 'StanAngeloff/php.vim', {'for': 'php'}
if v:version > 800
    Plug 'jalvesaq/Nvim-R', {'for': ['r', 'R']}
endif
Plug 'pangloss/vim-javascript', {'for': 'js'}

Plug 'johngrib/vim-game-code-break'
call plug#end()

" Color scheme
if empty(glob("$HOME/.vim/colors/jellybeans.vim"))
    silent !curl --fail --location --output $HOME/.vim/colors/jellybeans.vim --create-dirs https://raw.githubusercontent.com/nanotech/jellybeans.vim/master/colors/jellybeans.vim
endif
if has('syntax')
    syntax on
endif
colorscheme jellybeans

" CSV settings
map <C-d> :NewDelimiter

" SingleCompile settings
map <F12> :SingleCompile <Return>

" Undotree settings
nnoremap <F8> :UndotreeToggle <Return>

" Nerdtree settings
map <silent> <F9> :NERDTreeToggle <Return>
let NERDTreeQuitOnOpen = 1
let NERDTreeShowHidden = 1
let NERDTreeWinPos = "left"
let NERDTreeIgnore = ['\.pyc$', '\.swp$', '\.git$', '\.DS_Store$', '\.mypy_cache$']
let NERDTreeShowLineNumbers = 1

" Tagbar settings
map <silent> <F10> :TagbarToggle <Return>

" autoformat settings
nnoremap <silent> <leader>af :Autoformat <Return>
let g:formatdef_my_astyle = '"astyle --style=bsd --indent=spaces=4 --indent-preproc-block --indent-preproc-define --indent-col1-comments --pad-oper --pad-comma --unpad-paren --break-closing-braces --add-braces --attach-return-type --align-pointer=type --delete-empty-lines --add-one-line-braces --align-reference=type --break-blocks"'
let g:formatters_java = ['my_astyle']
let g:formatters_cpp = ['my_astyle']
let g:formatters_c = ['my_astyle']
let g:formatters_my_js = '"js-beautify --space-in-paren --space-after-anon-function --space-after-named-function --brace-style none";'
let g:formatters_js = ['my_js']
let g:formatdef_myautopep8 = '"autopep8 --ignore E501 --aggressive --aggressive -"'
let g:formatters_python = ['myautopep8']
let g:formatters_perl = ['perltidy']
autocmd FileType vim,tex let g:autoformat_autoindent=0

" syntastic settings
let g:syntastic_python_checkers = ['flake8', 'mypy']
let g:syntastic_python_flake8_args = '--ignore=E501'
let g:syntastic_python_mypy_args = '--ignore-missing-imports'

" indent and tab settings
filetype indent plugin on
set autoindent
set smartindent
set shiftwidth=4
set expandtab
set tabstop=4
set softtabstop=4

" change Tab to Space
autocmd FileType c retab
autocmd FileType cpp retab
autocmd FileType py retab

" general settings
set wrap
set linebreak
set showbreak=·····
set ruler
set cursorline
set laststatus=2
set showcmd
set showmatch
set matchtime=3
set autoread
set scrolloff=3
set wildmenu
set wildmode=longest:full,full
set noshowmode
set relativenumber
set number
set hidden
set wildignore+=*.swp,*.pyc,.mypy_cache,.git,.DS_Store
set backspace=indent,eol,start
set list
set listchars=tab:⇥\ ,trail:·,precedes:«,extends:»,eol:¶
set background=dark
set title

" backup settings
set nobackup
set nowritebackup
set noswapfile

" search settings
set ignorecase
set smartcase
set hlsearch
set incsearch
set showcmd

" status line settings
set statusline=\ %<%l:%v\ [%P]%=%a\ %h%m%r\ %F\

" use OS clipboard
set clipboard=unnamed

" use mouse
if has('mouse')
    set mouse=a
endif

" airline settings
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#right_sep = ''
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline#extensions#tabline#buffer_nr_show = 1
let g:airline#extensions#tabline#buffer_nr_format = '%s:'

" Tab settings
nnoremap <C-t> :enew <Return>
nnoremap <silent> <C-h> :bprevious <Return>
nnoremap <silent> <C-l> :bnext <Return>
nnoremap <silent> <C-q> :bprevious <BAR> bdelete #<Return>

" keymap
nnoremap <silent> <SPACE> :set hlsearch! <Return>
nnoremap <C-w>m :split <Return>
nnoremap <C-w>l :vsplit <Return>
nnoremap <C-n> "=strftime("%Y-%m-%d")<Return>p
nnoremap <C-m> "=strftime("%FT%T%z")<Return>p
command! GetPDF hardcopy > %.ps | !ps2pdf %.ps && rm %.ps && echo 'Created: %.pdf'
