[[ -o INTERACTIVE && -t 2 ]] && {

    SAYINGS=(
        "So long and thanks for all the fish.\n  -- Douglas Adams"
        "Good morning! And in case I don't see ya, good afternoon, good evening and goodnight.\n  -- Truman Burbank"
        "As it was in the beginning, is now, and ever shall be, world without end. R'Amen.\n  -- Gloria Patri"
        "I spent my whole life trying not to be careless. Children can be careless, but not the Bishop.\n -- God Father"
        "If one remains not annoyed when he is not understood by people around him, isn't he a sage?\n -- Analects"
        "He who leads flocks has no right to think about himself.\n -- Walter Model"
    )

# Print a randomly-chosen message:
echo $SAYINGS[$(($RANDOM % ${#SAYINGS} + 1))]

} >&2
