[[ -o INTERACTIVE && -t 2 ]] && {

    SAYINGS=(
        "So long and thanks for all the fish.\n  -- Douglas Adams"
        "Good morning! And in case I don't see ya, good afternoon, good evening and goodnight.\n  -- Truman Burbank"
        "As it was in the beginning, is now, and ever shall be, world without end. R'Amen.\n  -- Gloria Patri"
    )

# Print a randomly-chosen message:
echo $SAYINGS[$(($RANDOM % ${#SAYINGS} + 1))]

} >&2
