stty -ixon
export ZSH=${ZDOTDIR:-$HOME}/.oh-my-zsh
source ${ZSH}/oh-my-zsh.sh

# choose theme
if [[ -n "$SSH_CONNECTION" ]]; then
  ZSH_THEME="remote"
else
  ZSH_THEME="local"
fi

# plugins
plugins=(
    git
    vi-mode
    zsh-syntax-highlighting
    ssh-agent
)

# editors
export EDITOR="vim"
export VISUAL="vim"
export PAGER="less"

export TERM="xterm-256color"
export SGE_ROOT="/opt/Gridengine"

# ssh
export SSH_KEY_PATH="${ZDOTDIR:-$HOME}/.ssh/id_rsa"
zstyle :omz:plugins:ssh-agent identities id_rsa
zstyle :omz:plugins:ssh-agent lifetime 1h
if [[ `uname` == "Darwin" ]]; then
    export SSH_ASKPASS=touch2sudo
fi

# locale setting
if [[ -z "$LC_ALL" ]]; then
    export LC_ALL="en_US.UTF-8"
fi
if [[ -z "$LANG" ]]; then
    export LANG="en_US.UTF-8"
fi

# alias
if [[ -f "${ZDOTDIR:-$HOME}/.alias.zsh" ]]; then
    source ${ZDOTDIR:-$HOME}/.alias.zsh
fi

# multiple line command
autoload -U edit-command-line
zle -N edit-command-line
bindkey "^xe" edit-command-line
bindkey "^x^e" edit-command-line

# PATH settings
export PATH="/usr/local/sbin:${PATH}"
export PATH="${ZDOTDIR:-$HOME}/.local/bin:${PATH}"

# gpg settings
export GPG_TTY=$(tty)
if [[ `uname` == "Darwin" ]]; then
    eval "$(gpg-agent)" > /dev/null
fi
