stty -ixon

# choose theme
if [[ -n "$SSH_CONNECTION" ]]; then
    ZSH_THEME="remote"
else
    ZSH_THEME="local"
fi

# Soure oh-my-zsh *after* THEME
export ZSH=${ZDOTDIR:-$HOME}/.oh-my-zsh
source ${ZSH}/oh-my-zsh.sh

# plugins
plugins=(
    git
    vi-mode
    zsh-syntax-highlighting
    ssh-agent
)

# editors
if [[ $(uname) == "Darwin" ]]; then
    export EDITOR=$(which nvim)
    export VISUAL=$(which nvim)
else
    export EDITOR=$(which vim)
    export VISUAL=$(which vim)
fi
export PAGER=$(which less)

if [[ -z "$TERM" ]]; then
    export TERM="xterm-256color"
fi

# ssh
export SSH_KEY_PATH="${ZDOTDIR:-$HOME}/.ssh/id_rsa"
zstyle :omz:plugins:ssh-agent identities id_rsa
zstyle :omz:plugins:ssh-agent lifetime 12h

# locale setting
if [[ -z "$LC_ALL" ]]; then
    export LC_ALL="en_US.UTF-8"
fi
if [[ -z "$LANG" ]]; then
    export LANG="en_US.UTF-8"
fi

# alias
if [[ -f "${ZDOTDIR:-$HOME}/.alias.zsh" ]]; then
    source ${ZDOTDIR:-$HOME}/.alias.zsh
fi

# multiple line command
autoload -U edit-command-line
zle -N edit-command-line
bindkey "^xe" edit-command-line
bindkey "^x^e" edit-command-line

# PATH settings
export PATH="/usr/local/sbin:${PATH}"
export PATH="${ZDOTDIR:-$HOME}/.local/bin:${PATH}"

# gpg settings
export GPG_TTY=$(tty)

# git status
function __git_prompt_git () {
    GIT_OPTIONAL_LOCKS=0 command timeout 0.1s git "$@"
}
