name: macOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

    - name: check brew
      run: make mac_run

    - name: check ZSH
      run: make zsh_run

    - name: check oh-my-zsh
      run: make oh-my-zsh_run

    - name: check VIM
      run: make vim_run
