name: macOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: check update
        run: brew update && brew upgrade

      - name: check brew
        run: make mac_run

      - name: check ZSH
        run: make zsh_run

      - name: check oh-my-zsh
        run: make oh-my-zsh_run

      - name: check VIM
        run: make vim_run
