name: Ubuntu CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

    - name: install ZSH
      run: sudo apt-get update && sudo apt-get install zsh -y && sudo chsh -s $(which zsh) $(whoami)

    - name: check ZSH
      run: make zsh_run

    - name: check oh-my-zsh
      run: make oh-my-zsh_run

    - name: check VIM
      run: make vim_run
