name: Ubuntu CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: install ZSH
      run: sudo apt-get update && sudo apt-get install zsh -y

    - name: check ZSH
      run: make zsh_run
      shell: zsh {0}
      
    - name: check oh-my-zsh
      run: make oh-my-zsh_run
      shell: zsh {0}
      
    - name: check VIM
      run: make vim_run
      shell: zsh {0}
